# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Convivio
email: hello@weareconvivio.com
description: > # this means to ignore newlines until "baseurl:"
  We do digital strategy, design, and development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weareconvivio.com" # the base hostname & protocol for your site
twitter_username: weareconvivio
github_username:  ConvivioTeam
repository: ConvivioTeam/Convivio-Site

# Build settings
markdown: kramdown

exclude: [vendor]

# Sass compile settings
sass:
  style: compressed

